### ISSUE TITLE
Question about the usage of GPU memory

### ISSUE THREAD

**Issue by zzzack66** [yzbouc/UVEB#6]
Hi there,
Thanks for your awesome work! The dataset you constructed will be of great help to the field of underwater video enhancement. 
It is reported in the paper that the UVE-Net is trained on 4 48GB GPUs. I'm wondering the usage of GPU memory for UVE-Net and UVE-Net-s and the eta training time for the UVEB dataset under your experimental settings. Can I train your network on 2 4090 GPUs?
Thanks for your attention. I'm looking forward to your reply.

**Comment by yzbouc** [comment]
I think 24GB of memory is enough to train the small model. If you want to train a large model, you may need to set the batch size or patch_size (gt_size) in the yaml file to a smaller size in the options folder, and the num_frame can also be adjusted. During testing, the corresponding num_frame of yaml can be set to 1 for inference 4k frames. In fact, during testing, in order to maintain consistency with the training, we inferred three frames simultaneously, and the graphics card memory occupied about 33GB.

**Comment by yzbouc** [comment]
I think 24GB of memory is enough to train the small model. If you want to train the big model, you may need to set the batch size or patch_size (gt_size) in the yaml file of the options folder to a smaller size,  and the num_frame can also be adjusted. During testing, the corresponding num_frame of yaml can be set to 1 for inference 4k frames. In fact, during testing, in order to maintain consistency with the training, we inferred three frames simultaneously, and the graphics card memory occupied about 33GB.
